name: Update image simple-web-uuid

on:
  repository_dispatch:
    types: ["update-image-simple-web-uuid"]

permissions:
  contents: write
  pull-requests: write

env:
  IMAGE_NAME: ${{ github.event.client_payload.image_name }}

jobs:
  update-image-simple-web-uuid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN_PR_KUBERNETES_MANIFESTS_PUBLIC }}

      - name: Configure Git identity
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update image
        run: |
          sed -i \
            "s|image:.*|image: ${IMAGE_NAME}|" \
          ./simple-web-uuid/manifests/deploy.yaml

      - name: Create pull request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.TOKEN_PR_KUBERNETES_MANIFESTS_PUBLIC }}
          title: "Update simple-web-uuid image to ${{ env.IMAGE_NAME }}"
          commit-message: "update simple-web-uuid image"
          branch: update-simple-web-uuid-image
          delete-branch: true
          committer: "GitHub Actions Bot <41898282+github-actions[bot]@users.noreply.github.com>"
          author: "GitHub Actions Bot <41898282+github-actions[bot]@users.noreply.github.com>
          body: |
            Update simple-web-uuid image
            Image name: `${{ github.event.client_payload.image_name }}`

      - name: Auto pull request approve
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.TOKEN_PR_KUBERNETES_MANIFESTS_PUBLIC }}
          pull-request-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
